/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shadow (https://sketchfab.com/jaydenelizondo7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-2898a4b265d943919ca830e7d746ac13
Title: Little-astronaut
*/

import React, { use, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'
import { useMotionValue, useSpring } from 'motion/react'
export function Galaxy(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/little-astronaut.glb')
  const { actions } = useAnimations(animations, group)
useEffect(() => {
    // Set all animation tracks to use smooth interpolation
    if (animations.length > 0) {
      actions[animations[4].name]?.play()
    }
  }, [actions, animations])

  const yPosition = useMotionValue(5)
  const ySpring = useSpring(yPosition, {damping : 30})
  useEffect(() => {
    ySpring.set(-1.1)
  }, [ySpring])
useFrame(() => {
    group.current.position.y = ySpring.get();
  })
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2.2, 0.5, 0.4]}
      scale={props.scale ||2}
      position={props.position || [0.7, -1.1, 0.4]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="astronautfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Astronaut"
                  position={[0, 76.083, 0]}
                />
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.Astronaut}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[0, 76.083, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/little-astronaut.glb')